import jakaria from "../images/FoundersImages/md-golam-jakaria.jpg";
import fahim from '../images/FoundersImages/fahim-hossain.jpg';
import asraful from "../images/FoundersImages/asraful-Islam.jpg";
import nirob from "../images/FoundersImages/nirob-das.jpg";
import miraz from "../images/FoundersImages/nirob-das.jpg"
const foundersData=[
    {
        id: 1,
        name: "Md.Golam Jakaria",
        image: jakaria ,
        designetion:"Founder",
        altranetiveDesignetion:"ceo,cfo",
        bio: "BLA BLA BLA BLA",
        phone: "01963976449",
        homeNum:"01941471318",
        email:"jakaria3335@gmail.com",
        fatherName : "Abdul Mannan Khan",
        fatherNidnumber:"Pending",
        motherName : 'Halima Akter',
        motherNidNumber:"6817684464802",
        maritalStatus:'unmarrid',
        wifeName:'',
        wifeNidNumber:"",
        birth:"10/12/1999",
        birthCertificateNumber:"19996817684100793",
        nidNumber:'8254694337',
        passportNumber:"BX0582352",
        presentAddress:"253, West Agargaon, Sher-e-Bangla Nagor, Dhaka-1207, Banglaesh",
        permanentAddress:"Vill: Kumradi, PO: Kumradi, PS: Shibpur, Dist: Narsingdi, Bangladesh",
        nomineName:"Abdul Mannan Khan",
        nomineRelation:"Father",
        nomineImage:"",
        nominePhone:"01903571392",


    },
    {
        id: 2,
        name: "Tarif Hossain Fahim",
        image: fahim , 
        designetion:"Founder",
        altranetiveDesignetion:"coo",
        bio: "BLA BLA BLA BLA",
        phone: "01642369706",
        homeNum:"01638735056",
        email:"fahimjr44@gmail.com",
        fatherName : "Akhter Hossen",
        fatherNidnumber:"Pending",
        motherName : 'Ruji Akter',
        motherNidNumber:"Pending",
        maritalStatus:'unmarrid',
        wifeName:'',
        wifeNidNumber:"",
        birth:"Pending",
        birthCertificateNumber:"19996825006831858",
        nidNumber:'Still baby',
        passportNumber:"None",
        presentAddress:"66/3, UMC Road, Sathirpara, Narsingdi sadar, Narsingdi",
        permanentAddress:"66/3, UMC Road, Sathirpara, Narsingdi sadar, Narsingdi",
        nomineName:"Sanjida Akter",
        nomineRelation:"Sister",
        nomineImage:"",
        nominePhone:"01638735056",

    },
    {
        id: 3,
        name: "Asraful Islam",
        image: asraful,
        designetion:"Founder",
        altranetiveDesignetion:"cio",
        bio: "BLA BLA BLA BLA",
        phone: "01303692321",
        homeNum:"01798865148",
        email:"asraful33355@gmail.com",
        fatherName : "Md. Auyal Mia",
        fatherNidnumber:"Pending",
        motherName : 'Selina Begum',
        motherNidNumber:"Pending",
        maritalStatus:'unmarrid',
        wifeName:'',
        wifeNidNumber:"",
        birth:"Pending",
        birthCertificateNumber:"20006820206002170",
        nidNumber:'None',
        passportNumber:"None",
        presentAddress:"South Sathirpara, Narsingdi Sadar, Narsingdi",
        permanentAddress:"South Sathirpara, Narsingdi Sadar, Narsingdi",
        nomineName:"Silpi Akter",
        nomineRelation:"Aunty",
        nomineImage:"",
        nominePhone:"pending",

    },
    {
        id: 4,
        name: "Nirob Das",
        image: nirob,
        designetion:"Founder",
        altranetiveDesignetion:"cao",
        bio: "BLA BLA BLA BLA",
        phone: "01992405406",
        homeNum:"01624333871",
        email:"nirobdas1999@gmail.com",
        fatherName : "Subol Das",
        fatherNidnumber:"Pending",
        motherName : 'Sila Das',
        motherNidNumber:"Pending",
        maritalStatus:'unmarrid',
        wifeName:'',
        wifeNidNumber:"",
        birth:"Pending",
        birthCertificateNumber:"19996825006831702",
        nidNumber:'None',
        passportNumber:"None",
        presentAddress:"309/3, South Sathirpara, Narsingdi Sadar, Narsingdi",
        permanentAddress:"309/3, South Sathirpara, Narsingdi Sadar, Narsingdi",
        nomineName:"Samyo Das Syumik",
        nomineRelation:"Brother",
        nomineImage:"",
        nominePhone:"pending",

    },
    {
        id: 5,
        name: miraz,
        image:"",
        designetion:"Founder",
        altranetiveDesignetion:"cao, Investor",
        bio: "BLA BLA BLA BLA",
        phone: "01688017557",
        homeNum:"01817535421",
        email:"akashhq96@gmail.com",
        fatherName : "Ajharul Haq",
        fatherNidnumber:"Pending",
        motherName : 'Umme Kulsum Khanom',
        motherNidNumber:"Pending",
        maritalStatus:'unmarrid',
        wifeName:'',
        wifeNidNumber:"",
        birth:"11/12/1998",
        birthCertificateNumber:"Pending",
        nidNumber:'2405246279',
        passportNumber:"None",
        presentAddress:"210/9, Basail, Narsingdi Sadar, Narsingdi, Bangladesh",
        permanentAddress:"210/9, Basail, Narsingdi Sadar, Narsingdi, Bangladesh",
        nomineName:"Ajharul hoq",
        nomineRelation:"father",
        nomineImage:"",
        nominePhone:"01817535421",

    },
]
export default foundersData;