const investorsData=[
    {
        id: 1,
        name: "Mirazul Islam Miraz",
        image:"",
        designetion:"Investor",
        investAmount:50000,
        investDate: "01/02/2020",
        profitpercentage:0.2,
        altranetiveDesignetion:"CAO",
        bio: "BLA BLA BLA BLA",
        phone: "01688017557",
        homeNum:"01817535421",
        email:"akashhq96@gmail.com",
        fatherName : "Ajharul Haq",
        fatherNidnumber:"Pending",
        motherName : 'Umme Kulsum Khanom',
        motherNidNumber:"Pending",
        maritalStatus:'unmarrid',
        wifeName:'',
        wifeNidNumber:"",
        birth:"11/12/1998",
        birthCertificateNumber:"Pending",
        nidNumber:'2405246279',
        passportNumber:"None",
        presentAddress:"210/9, Basail, Narsingdi Sadar, Narsingdi, Bangladesh",
        permanentAddress:"210/9, Basail, Narsingdi Sadar, Narsingdi, Bangladesh",
        nomineName:"Ajharul hoq",
        nomineRelation:"father",
        nomineImage:"",
        nominePhone:"01817535421",

    },
]
export default investorsData;